### ISSUE TITLE
Info for update

### ISSUE THREAD

**Issue by docop** [awesometic/realtek-r8152-dkms#1]
Hi  So thank for the driver, it look quite simple and not to used build something or so.
 As the used, if i install on debian 11 , then do update and so.. when we gonna update to debian 12. The driver will still be the same without any other package to re-install ?

Thanks

**Comment by docop** [comment]
Oh and is it only for debian or xubuntu can be install to ?

**Comment by awesometic** [comment]
Hi,

Yes, if you have installed this driver using DKMS, which is the default when you install its Debian package, then the driver will be the same after upgrading to Debian 12.

And you can install this package on every Debian based Linux distribution including Xubuntu.
If you cannot, please let me know, because it should be as I know.

**Comment by awesometic** [comment]
Since there is no conversation here after June, I will close this issue. :)
