### ISSUE TITLE
realtek-r8152 dkms broken after kernel upgrade

### ISSUE THREAD

**Issue by bp0** [awesometic/realtek-r8152-dkms#18]
Using the debian package `realtek-r8152-dkms_2.17.1-3_amd64.deb` with Proxmox 8.1 om a Dell Optiplex 3050 Micro.

After a kernel update, the r8152 USB driver failed to load with the message:
```
r8152: disagrees about version of symbol module_layout
```
Output of dkms-status:
```
realtek-r8152/2.17.1, 6.5.11-8-pve, amd64: installed
realtek-r8152/2.17.1, 6.5.13-1-pve, x86_64: installed
```

Fixed by:
```
apt remove realtek-r8152
dpkg -i realtek-r8152-dkms_2.17.1-3_amd64.deb
```

It is headless so it is a bit of a hassle to fix without network.

**Comment by naz9ul** [comment]
Always install the new kernel headers with the new proxmox kernel,  that Will help !

**Comment by bp0** [comment]
It seems the new headers were installed along with the new kernel but something got confused about what the arch was called. 
After re-install dkms-status shows:
```
realtek-r8152/2.17.1, 6.5.13-1-pve, amd64: installed
```
Notice that it is back to amd64 instead of x86_64.

**Comment by awesometic** [comment]
With the new kernel, it needs to be compiled again for the signature of the module.
Re-installing the package you did performs this job, so maybe it might work rebuilding using `dkms` command instead of reinstalling the whole package.

Generally `amd64` is treated as the same architecture to `x86_64`, that's just how it calls I believe.. 🤔 

If the issue solved, please close this one 😄

**Comment by awesometic** [comment]
Hello, since the issue has not been active for so long time so I will close this issue. Please re-open an issue if you face a problem 😄
